language: rust
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
notifications:
  irc:
    channels:
      - "irc.esper.net#FTB-Wiki-Dev"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
